const translations = {
    bg: {
        title: "Изберете вашата държава",
        contact: "Контакт",
        placeholder: "Въведете вашата страна",
    },
    hr: {
        title: "Odaberite svoju državu",
        contact: "Kontakt",
        placeholder: "Upisati državu",
    },
    cs: {
        title: "Vyberte svou zemi",
        contact: "Kontakt",
        placeholder: "Zadejte svou zemi",
    },
    da: {
        title: "Vælg dit land",
        contact: "Kontakt",
        placeholder: "Indtast dit land",
    },
    nl: { title: "Kies uw land", contact: "Contact", placeholder: "Typ uw land" },
    en: {
        title: "Choose your country",
        contact: "Contact",
        placeholder: "Type your country",
    },
    et: {
        title: "Valige oma riik",
        contact: "Kontakt",
        placeholder: "Sisestage oma riik",
    },
    fi: {
        title: "Valitse maasi",
        contact: "Ota yhteyttä",
        placeholder: "Kirjoita maasi",
    },
    fr: {
        title: "Choisissez votre pays",
        contact: "Contact",
        placeholder: "Tapez votre pays",
    },
    de: {
        title: "Wählen Sie Ihr Land",
        contact: "Kontakt",
        placeholder: "Geben Sie Ihr Land ein",
    },
    el: {
        title: "Επιλέξτε τη χώρα σας",
        contact: "Επικοινωνία",
        placeholder: "Πληκτρολογήστε τη χώρα σας",
    },
    hu: {
        title: "Válassza ki az országot",
        contact: "Kapcsolat",
        placeholder: "Írja be az ország nevét",
    },
    ga: {
        title: "Roghnaigh do thír",
        contact: "Teagmháil",
        placeholder: "Clóscríobh d’thír",
    },
    it: {
        title: "Scegli il tuo paese",
        contact: "Contatto",
        placeholder: "Digita il tuo paese",
    },
    lv: {
        title: "Izvēlieties savu valsti",
        contact: "Kontakts",
        placeholder: "Ierakstiet savu valsti",
    },
    lt: {
        title: "Pasirinkite savo šalį",
        contact: "Kontaktai",
        placeholder: "Įveskite savo šalį",
    },
    mt: {
        title: "Agħżel il-pajjiż tiegħek",
        contact: "Kuntatt",
        placeholder: "Ikteb il-pajjiż tiegħek",
    },
    pl: {
        title: "Wybierz swój kraj",
        contact: "Kontakt",
        placeholder: "Wpisz swój kraj",
    },
    pt: {
        title: "Escolha o seu país",
        contact: "Contacto",
        placeholder: "Digite o seu país",
    },
    ro: {
        title: "Alegeți țara dvs.",
        contact: "Contact",
        placeholder: "Tastați țara dvs.",
    },
    sk: {
        title: "Vyberte svoju krajinu",
        contact: "Kontakt",
        placeholder: "Zadajte svoju krajinu",
    },
    sl: {
        title: "Izberite svojo državo",
        contact: "Kontakt",
        placeholder: "Vnesite svojo državo",
    },
    es: {
        title: "Elija su país",
        contact: "Contacto",
        placeholder: "Escriba su país",
    },
    sv: {
        title: "Välj ditt land",
        contact: "Kontakt",
        placeholder: "Skriv ditt land",
    },
};

const countryTranslations = {
  bg: {
    Austria: "Австрия",
    Belgium: "Белгия",
    Bulgaria: "България",
    Croatia: "Хърватия",
    Cyprus: "Кипър",
    Czechia: "Чехия",
    Denmark: "Дания",
    Estonia: "Естония",
    Finland: "Финландия",
    France: "Франция",
    Germany: "Германия",
    Greece: "Гърция",
    Hungary: "Унгария",
    Ireland: "Ирландия",
    Italy: "Италия",
    Latvia: "Латвия",
    Lithuania: "Литва",
    Luxembourg: "Люксембург",
    Malta: "Малта",
    Netherlands: "Нидерландия",
    Poland: "Полша",
    Portugal: "Португалия",
    Romania: "Румъния",
    Slovakia: "Словакия",
    Slovenia: "Словения",
    Spain: "Испания",
    Sweden: "Швеция",
  },
  hr: {
    Austria: "Austrija",
    Belgium: "Belgija",
    Bulgaria: "Bugarska",
    Croatia: "Hrvatska",
    Cyprus: "Cipar",
    Czechia: "Češka",
    Denmark: "Danska",
    Estonia: "Estonija",
    Finland: "Finska",
    France: "Francuska",
    Germany: "Njemačka",
    Greece: "Grčka",
    Hungary: "Mađarska",
    Ireland: "Irska",
    Italy: "Italija",
    Latvia: "Latvija",
    Lithuania: "Litva",
    Luxembourg: "Luksemburg",
    Malta: "Malta",
    Netherlands: "Nizozemska",
    Poland: "Poljska",
    Portugal: "Portugal",
    Romania: "Rumunjska",
    Slovakia: "Slovačka",
    Slovenia: "Slovenija",
    Spain: "Španjolska",
    Sweden: "Švedska",
  },
  cs: {
    Austria: "Rakousko",
    Belgium: "Belgie",
    Bulgaria: "Bulharsko",
    Croatia: "Chorvatsko",
    Cyprus: "Kypr",
    Czechia: "Česko",
    Denmark: "Dánsko",
    Estonia: "Estonsko",
    Finland: "Finsko",
    France: "Francie",
    Germany: "Německo",
    Greece: "Řecko",
    Hungary: "Maďarsko",
    Ireland: "Irsko",
    Italy: "Itálie",
    Latvia: "Lotyšsko",
    Lithuania: "Litva",
    Luxembourg: "Lucembursko",
    Malta: "Malta",
    Netherlands: "Nizozemsko",
    Poland: "Polsko",
    Portugal: "Portugalsko",
    Romania: "Rumunsko",
    Slovakia: "Slovensko",
    Slovenia: "Slovinsko",
    Spain: "Španělsko",
    Sweden: "Švédsko",
  },
  da: {
    Austria: "Østrig",
    Belgium: "Belgien",
    Bulgaria: "Bulgarien",
    Croatia: "Kroatien",
    Cyprus: "Cypern",
    Czechia: "Tjekkiet",
    Denmark: "Danmark",
    Estonia: "Estland",
    Finland: "Finland",
    France: "Frankrig",
    Germany: "Tyskland",
    Greece: "Grækenland",
    Hungary: "Ungarn",
    Ireland: "Irland",
    Italy: "Italien",
    Latvia: "Letland",
    Lithuania: "Litauen",
    Luxembourg: "Luxembourg",
    Malta: "Malta",
    Netherlands: "Nederlandene",
    Poland: "Polen",
    Portugal: "Portugal",
    Romania: "Rumænien",
    Slovakia: "Slovakiet",
    Slovenia: "Slovenien",
    Spain: "Spanien",
    Sweden: "Sverige",
  },
  nl: {
    Austria: "Oostenrijk",
    Belgium: "België",
    Bulgaria: "Bulgarije",
    Croatia: "Kroatië",
    Cyprus: "Cyprus",
    Czechia: "Tsjechië",
    Denmark: "Denemarken",
    Estonia: "Estland",
    Finland: "Finland",
    France: "Frankrijk",
    Germany: "Duitsland",
    Greece: "Griekenland",
    Hungary: "Hongarije",
    Ireland: "Ierland",
    Italy: "Italië",
    Latvia: "Letland",
    Lithuania: "Litouwen",
    Luxembourg: "Luxemburg",
    Malta: "Malta",
    Netherlands: "Nederland",
    Poland: "Polen",
    Portugal: "Portugal",
    Romania: "Roemenië",
    Slovakia: "Slowakije",
    Slovenia: "Slovenië",
    Spain: "Spanje",
    Sweden: "Zweden",
  },
  en: {
    Austria: "Austria",
    Belgium: "Belgium",
    Bulgaria: "Bulgaria",
    Croatia: "Croatia",
    Cyprus: "Cyprus",
    Czechia: "Czechia",
    Denmark: "Denmark",
    Estonia: "Estonia",
    Finland: "Finland",
    France: "France",
    Germany: "Germany",
    Greece: "Greece",
    Hungary: "Hungary",
    Ireland: "Ireland",
    Italy: "Italy",
    Latvia: "Latvia",
    Lithuania: "Lithuania",
    Luxembourg: "Luxembourg",
    Malta: "Malta",
    Netherlands: "Netherlands",
    Poland: "Poland",
    Portugal: "Portugal",
    Romania: "Romania",
    Slovakia: "Slovakia",
    Slovenia: "Slovenia",
    Spain: "Spain",
    Sweden: "Sweden",
  },
  et: {
    Austria: "Austria",
    Belgium: "Belgia",
    Bulgaria: "Bulgaaria",
    Croatia: "Horvaatia",
    Cyprus: "Küpros",
    Czechia: "Tšehhi",
    Denmark: "Taani",
    Estonia: "Eesti",
    Finland: "Soome",
    France: "Prantsusmaa",
    Germany: "Saksamaa",
    Greece: "Kreeka",
    Hungary: "Ungari",
    Ireland: "Iirimaa",
    Italy: "Itaalia",
    Latvia: "Läti",
    Lithuania: "Leedu",
    Luxembourg: "Luxembourg",
    Malta: "Malta",
    Netherlands: "Madala",
    Poland: "Poola",
    Portugal: "Portugal",
    Romania: "Rumeenia",
    Slovakia: "Slovakkia",
    Slovenia: "Sloveenia",
    Spain: "Hispaania",
    Sweden: "Rootsi",
  },
  fi: {
    Austria: "Itävalta",
    Belgium: "Belgia",
    Bulgaria: "Bulgaria",
    Croatia: "Kroatia",
    Cyprus: "Kypros",
    Czechia: "Tšekki",
    Denmark: "Tanska",
    Estonia: "Viro",
    Finland: "Suomi",
    France: "Ranska",
    Germany: "Saksa",
    Greece: "Kreikka",
    Hungary: "Unkari",
    Ireland: "Irlanti",
    Italy: "Italia",
    Latvia: "Latvia",
    Lithuania: "Liettua",
    Luxembourg: "Luxemburg",
    Malta: "Malta",
    Netherlands: "Alankomaat",
    Poland: "Puola",
    Portugal: "Portugali",
    Romania: "Romania",
    Slovakia: "Slovakia",
    Slovenia: "Slovenia",
    Spain: "Espanja",
    Sweden: "Ruotsi",
  },
  fr: {
    Austria: "Autriche",
    Belgium: "Belgique",
    Bulgaria: "Bulgarie",
    Croatia: "Croatie",
    Cyprus: "Chypre",
    Czechia: "Tchéquie",
    Denmark: "Danemark",
    Estonia: "Estonie",
    Finland: "Finlande",
    France: "France",
    Germany: "Allemagne",
    Greece: "Grèce",
    Hungary: "Hongrie",
    Ireland: "Irlande",
    Italy: "Italie",
    Latvia: "Lettonie",
    Lithuania: "Lituanie",
    Luxembourg: "Luxembourg",
    Malta: "Malte",
    Netherlands: "Pays-Bas",
    Poland: "Pologne",
    Portugal: "Portugal",
    Romania: "Roumanie",
    Slovakia: "Slovaquie",
    Slovenia: "Slovénie",
    Spain: "Espagne",
    Sweden: "Suède",
  },
  de: {
    Austria: "Österreich",
    Belgium: "Belgien",
    Bulgaria: "Bulgarien",
    Croatia: "Kroatien",
    Cyprus: "Zypern",
    Czechia: "Tschechien",
    Denmark: "Dänemark",
    Estonia: "Estland",
    Finland: "Finnland",
    France: "Frankreich",
    Germany: "Deutschland",
    Greece: "Griechenland",
    Hungary: "Ungarn",
    Ireland: "Irland",
    Italy: "Italien",
    Latvia: "Lettland",
    Lithuania: "Litauen",
    Luxembourg: "Luxemburg",
    Malta: "Malta",
    Netherlands: "Niederlande",
    Poland: "Polen",
    Portugal: "Portugal",
    Romania: "Rumänien",
    Slovakia: "Slowakei",
    Slovenia: "Slowenien",
    Spain: "Spanien",
    Sweden: "Schweden",
  },
  el: {
    Austria: "Αυστρία",
    Belgium: "Βέλγιο",
    Bulgaria: "Βουλγαρία",
    Croatia: "Κροατία",
    Cyprus: "Κύπρος",
    Czechia: "Τσεχία",
    Denmark: "Δανία",
    Estonia: "Εσθονία",
    Finland: "Φινλανδία",
    France: "Γαλλία",
    Germany: "Γερμανία",
    Greece: "Ελλάδα",
    Hungary: "Ουγγαρία",
    Ireland: "Ιρλανδία",
    Italy: "Ιταλία",
    Latvia: "Λετονία",
    Lithuania: "Λιθουανία",
    Luxembourg: "Λουξεμβούργο",
    Malta: "Μάλτα",
    Netherlands: "Ολλανδία",
    Poland: "Πολωνία",
    Portugal: "Πορτογαλία",
    Romania: "Ρουμανία",
    Slovakia: "Σλοβακία",
    Slovenia: "Σλοβενία",
    Spain: "Ισπανία",
    Sweden: "Σουηδία",
  },
  hu: {
    Austria: "Ausztria",
    Belgium: "Belgium",
    Bulgaria: "Bulgária",
    Croatia: "Horvátország",
    Cyprus: "Ciprus",
    Czechia: "Csehország",
    Denmark: "Dánia",
    Estonia: "Észtország",
    Finland: "Finnország",
    France: "Franciaország",
    Germany: "Németország",
    Greece: "Görögország",
    Hungary: "Magyarország",
    Ireland: "Írország",
    Italy: "Olaszország",
    Latvia: "Lettország",
    Lithuania: "Litvánia",
    Luxembourg: "Luxemburg",
    Malta: "Málta",
    Netherlands: "Hollandia",
    Poland: "Lengyelország",
    Portugal: "Portugália",
    Romania: "Románia",
    Slovakia: "Szlovákia",
    Slovenia: "Szlovénia",
    Spain: "Spanyolország",
    Sweden: "Svédország",
  },
  ga: {
    Austria: "An Ostair",
    Belgium: "An Bheilg",
    Bulgaria: "An Bhulgáir",
    Croatia: "An Chróit",
    Cyprus: "An Chipir",
    Czechia: "An tSeice",
    Denmark: "An Danmhairg",
    Estonia: "An Eastóin",
    Finland: "An Fhionlainn",
    France: "An Fhrainc",
    Germany: "An Ghearmáin",
    Greece: "An Ghréig",
    Hungary: "An Ungáir",
    Ireland: "Éire",
    Italy: "An Iodáil",
    Latvia: "An Laitvia",
    Lithuania: "An Liotuáin",
    Luxembourg: "Lucsamburg",
    Malta: "Málta",
    Netherlands: "An Ísiltír",
    Poland: "An Pholainn",
    Portugal: "An Phortaingéil",
    Romania: "An Rómáin",
    Slovakia: "An tSlóvaic",
    Slovenia: "An tSlóivéin",
    Spain: "An Spáinn",
    Sweden: "An tSualainn",
  },
  it: {
    Austria: "Austria",
    Belgium: "Belgio",
    Bulgaria: "Bulgaria",
    Croatia: "Croazia",
    Cyprus: "Cipro",
    Czechia: "Repubblica Ceca",
    Denmark: "Danimarca",
    Estonia: "Estonia",
    Finland: "Finlandia",
    France: "Francia",
    Germany: "Germania",
    Greece: "Grecia",
    Hungary: "Ungheria",
    Ireland: "Irlanda",
    Italy: "Italia",
    Latvia: "Lettonia",
    Lithuania: "Lituania",
    Luxembourg: "Lussemburgo",
    Malta: "Malta",
    Netherlands: "Paesi Bassi",
    Poland: "Polonia",
    Portugal: "Portogallo",
    Romania: "Romania",
    Slovakia: "Slovacchia",
    Slovenia: "Slovenia",
    Spain: "Spagna",
    Sweden: "Svezia",
  },
  lv: {
    Austria: "Austrija",
    Belgium: "Beļģija",
    Bulgaria: "Bulgārija",
    Croatia: "Horvātija",
    Cyprus: "Kipra",
    Czechia: "Čehija",
    Denmark: "Dānija",
    Estonia: "Igaunija",
    Finland: "Somija",
    France: "Francija",
    Germany: "Vācija",
    Greece: "Grieķija",
    Hungary: "Ungārija",
    Ireland: "Īrija",
    Italy: "Itālija",
    Latvia: "Latvija",
    Lithuania: "Lietuva",
    Luxembourg: "Luksemburga",
    Malta: "Malta",
    Netherlands: "Nīderlande",
    Poland: "Polija",
    Portugal: "Portugāle",
    Romania: "Rumānija",
    Slovakia: "Slovākija",
    Slovenia: "Slovēnija",
    Spain: "Spānija",
    Sweden: "Zviedrija",
  },
  lt: {
    Austria: "Austrija",
    Belgium: "Belgija",
    Bulgaria: "Bulgarija",
    Croatia: "Kroatija",
    Cyprus: "Kipras",
    Czechia: "Čekija",
    Denmark: "Danija",
    Estonia: "Estija",
    Finland: "Suomija",
    France: "Prancūzija",
    Germany: "Vokietija",
    Greece: "Graikija",
    Hungary: "Vengrija",
    Ireland: "Airija",
    Italy: "Italija",
    Latvia: "Latvija",
    Lithuania: "Lietuva",
    Luxembourg: "Liuksemburgas",
    Malta: "Malta",
    Netherlands: "Nyderlandai",
    Poland: "Lenkija",
    Portugal: "Portugalija",
    Romania: "Rumunija",
    Slovakia: "Slovakija",
    Slovenia: "Slovėnija",
    Spain: "Ispanija",
    Sweden: "Švedija",
  },
  mt: {
    Austria: "Awstrija",
    Belgium: "Belġju",
    Bulgaria: "Bulgarja",
    Croatia: "Kroazja",
    Cyprus: "Ċipru",
    Czechia: "Repubblika Ċeka",
    Denmark: "Danimarka",
    Estonia: "Estonja",
    Finland: "Finlandja",
    France: "Franza",
    Germany: "Il-Ġermanja",
    Greece: "Il-Greċja",
    Hungary: "L-Ungerija",
    Ireland: "L-Irlanda",
    Italy: "L-Italja",
    Latvia: "Il-Latvja",
    Lithuania: "Il-Litwanja",
    Luxembourg: "Lussemburgu",
    Malta: "Malta",
    Netherlands: "In-Netherlands",
    Poland: "Il-Polonja",
    Portugal: "Il-Portugall",
    Romania: "Ir-Rumanija",
    Slovakia: "Is-Slovakkja",
    Slovenia: "Is-Slovenja",
    Spain: "Spanja",
    Sweden: "Iż-Svezja",
  },
  pl: {
    Austria: "Austria",
    Belgium: "Belgia",
    Bulgaria: "Bułgaria",
    Croatia: "Chorwacja",
    Cyprus: "Cypr",
    Czechia: "Czechy",
    Denmark: "Dania",
    Estonia: "Estonia",
    Finland: "Finlandia",
    France: "Francja",
    Germany: "Niemcy",
    Greece: "Grecja",
    Hungary: "Węgry",
    Ireland: "Irlandia",
    Italy: "Włochy",
    Latvia: "Łotwa",
    Lithuania: "Litwa",
    Luxembourg: "Luksemburg",
    Malta: "Malta",
    Netherlands: "Holandia",
    Poland: "Polska",
    Portugal: "Portugalia",
    Romania: "Rumunia",
    Slovakia: "Słowacja",
    Slovenia: "Słowenia",
    Spain: "Hiszpania",
    Sweden: "Szwecja",
  },
  pt: {
    Austria: "Áustria",
    Belgium: "Bélgica",
    Bulgaria: "Bulgária",
    Croatia: "Croácia",
    Cyprus: "Chipre",
    Czechia: "Chéquia",
    Denmark: "Dinamarca",
    Estonia: "Estónia",
    Finland: "Finlândia",
    France: "França",
    Germany: "Alemanha",
    Greece: "Grécia",
    Hungary: "Hungria",
    Ireland: "Irlanda",
    Italy: "Itália",
    Latvia: "Letónia",
    Lithuania: "Lituânia",
    Luxembourg: "Luxemburgo",
    Malta: "Malta",
    Netherlands: "Países Baixos",
    Poland: "Polónia",
    Portugal: "Portugal",
    Romania: "Roménia",
    Slovakia: "Eslováquia",
    Slovenia: "Eslovénia",
    Spain: "Espanha",
    Sweden: "Suécia",
  },
  ro: {
    Austria: "Austria",
    Belgium: "Belgia",
    Bulgaria: "Bulgaria",
    Croatia: "Croația",
    Cyprus: "Cipru",
    Czechia: "Cehia",
    Denmark: "Danemarca",
    Estonia: "Estonia",
    Finland: "Finlanda",
    France: "Franța",
    Germany: "Germania",
    Greece: "Grecia",
    Hungary: "Ungaria",
    Ireland: "Irlanda",
    Italy: "Italia",
    Latvia: "Letonia",
    Lithuania: "Lituania",
    Luxembourg: "Luxemburg",
    Malta: "Malta",
    Netherlands: "Olanda",
    Poland: "Polonia",
    Portugal: "Portugalia",
    Romania: "România",
    Slovakia: "Slovacia",
    Slovenia: "Slovenia",
    Spain: "Spania",
    Sweden: "Suedia",
  },
  sk: {
    Austria: "Rakúsko",
    Belgium: "Belgicko",
    Bulgaria: "Bulharsko",
    Croatia: "Chorvátsko",
    Cyprus: "Cyprus",
    Czechia: "Česko",
    Denmark: "Dánsko",
    Estonia: "Estónsko",
    Finland: "Fínsko",
    France: "Francúzsko",
    Germany: "Nemecko",
    Greece: "Grécko",
    Hungary: "Maďarsko",
    Ireland: "Írsko",
    Italy: "Taliansko",
    Latvia: "Lotyšsko",
    Lithuania: "Litva",
    Luxembourg: "Luxembursko",
    Malta: "Malta",
    Netherlands: "Holandsko",
    Poland: "Poľsko",
    Portugal: "Portugalsko",
    Romania: "Rumunsko",
    Slovakia: "Slovensko",
    Slovenia: "Slovinsko",
    Spain: "Španielsko",
    Sweden: "Švédsko",
  },
  sl: {
    Austria: "Avstrija",
    Belgium: "Belgija",
    Bulgaria: "Bolgarija",
    Croatia: "Hrvaška",
    Cyprus: "Ciper",
    Czechia: "Češka",
    Denmark: "Danska",
    Estonia: "Estonija",
    Finland: "Finska",
    France: "Francija",
    Germany: "Nemčija",
    Greece: "Grčija",
    Hungary: "Madžarska",
    Ireland: "Irska",
    Italy: "Italija",
    Latvia: "Latvija",
    Lithuania: "Litva",
    Luxembourg: "Luxemburg",
    Malta: "Malta",
    Netherlands: "Nizozemska",
    Poland: "Poljska",
    Portugal: "Portugalska",
    Romania: "Romunija",
    Slovakia: "Slovaška",
    Slovenia: "Slovenija",
    Spain: "Španija",
    Sweden: "Švedska",
  },
  es: {
    Austria: "Austria",
    Belgium: "Bélgica",
    Bulgaria: "Bulgaria",
    Croatia: "Croacia",
    Cyprus: "Chipre",
    Czechia: "Chequia",
    Denmark: "Dinamarca",
    Estonia: "Estonia",
    Finland: "Finlandia",
    France: "Francia",
    Germany: "Alemania",
    Greece: "Grecia",
    Hungary: "Hungría",
    Ireland: "Irlanda",
    Italy: "Italia",
    Latvia: "Letonia",
    Lithuania: "Lituania",
    Luxembourg: "Luxemburgo",
    Malta: "Malta",
    Netherlands: "Países Bajos",
    Poland: "Polonia",
    Portugal: "Portugal",
    Romania: "Rumanía",
    Slovakia: "Eslovaquia",
    Slovenia: "Eslovenia",
    Spain: "España",
    Sweden: "Suecia",
  },
  sv: {
    Austria: "Österrike",
    Belgium: "Belgien",
    Bulgaria: "Bulgarien",
    Croatia: "Kroatien",
    Cyprus: "Cypern",
    Czechia: "Tjeckien",
    Denmark: "Danmark",
    Estonia: "Estland",
    Finland: "Finland",
    France: "Frankrike",
    Germany: "Tyskland",
    Greece: "Grekland",
    Hungary: "Ungern",
    Ireland: "Irland",
    Italy: "Italien",
    Latvia: "Lettland",
    Lithuania: "Litauen",
    Luxembourg: "Luxemburg",
    Malta: "Malta",
    Netherlands: "Nederländerna",
    Poland: "Polen",
    Portugal: "Portugal",
    Romania: "Rumänien",
    Slovakia: "Slovakien",
    Slovenia: "Slovenien",
    Spain: "Spanien",
    Sweden: "Sverige",
  }
};


function applyTranslations(lang) {
    const dict = translations[lang] || translations.en;
    document.documentElement.lang = lang;

    const titleEl = document.getElementById("Title");
    if (titleEl) titleEl.textContent = dict.title;

    const contactEl = document.querySelector("[data-i18n='contact']") || document.querySelector(".nav_link");
    if (contactEl) contactEl.textContent = dict.contact;

    const inputEl = document.getElementById("countryInput");
    if (inputEl) inputEl.placeholder = dict.placeholder;

    const datalist = document.getElementById("euCountries");
    datalist.innerHTML = ""; 

    const countries = Object.keys(countryTranslations.en); // English country names
    countries.forEach(country => {
        const option = document.createElement("option");
        option.value = dict[country] || country; // translated or fallback
        datalist.appendChild(option);
    });
}

// Detect browser language and apply
document.addEventListener("DOMContentLoaded", () => {
    const fullLang = navigator.language || navigator.userLanguage || "en";
    const shortLang = fullLang.slice(0, 2).toLowerCase();
    const langToUse = translations[shortLang] ? shortLang : "en";
    applyTranslations(langToUse);
});
